/**
 * Standardized error codes across all REZ services and apps.
 */
export const ERROR_CODES = {
  // Auth
  AUTH_EXPIRED: 'AUTH_EXPIRED',
  AUTH_INVALID: 'AUTH_INVALID',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',

  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

  // Rate Limiting
  RATE_LIMITED: 'RATE_LIMITED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // Resources
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  CONFLICT: 'CONFLICT',

  // Financial
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  WITHDRAWAL_LIMIT_EXCEEDED: 'WITHDRAWAL_LIMIT_EXCEEDED',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',

  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  TIMEOUT: 'TIMEOUT',
  MAINTENANCE: 'MAINTENANCE',

  // CSRF
  CSRF_INVALID: 'CSRF_INVALID',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];

/** Map error codes to default HTTP status codes */
export const ERROR_STATUS_MAP: Record<ErrorCode, number> = {
  AUTH_EXPIRED: 401,
  AUTH_INVALID: 401,
  AUTH_FORBIDDEN: 403,
  AUTH_ACCOUNT_LOCKED: 423,
  AUTH_ACCOUNT_SUSPENDED: 403,
  VALIDATION_FAILED: 400,
  INVALID_INPUT: 400,
  MISSING_REQUIRED_FIELD: 400,
  RATE_LIMITED: 429,
  TOO_MANY_REQUESTS: 429,
  NOT_FOUND: 404,
  ALREADY_EXISTS: 409,
  CONFLICT: 409,
  INSUFFICIENT_BALANCE: 402,
  PAYMENT_FAILED: 402,
  WITHDRAWAL_LIMIT_EXCEEDED: 400,
  TRANSACTION_FAILED: 500,
  INTERNAL_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
  TIMEOUT: 504,
  MAINTENANCE: 503,
  CSRF_INVALID: 403,
};
